# Generated by Django 3.1.7 on 2021-11-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque_voiture', models.CharField(max_length=30, null=True)),
                ('modele_du_voiture', models.CharField(max_length=30, null=True)),
                ('image_de_voiture', models.ImageField(blank=True, upload_to='')),
                ('date_de_l_annonce', models.DateTimeField(auto_now_add=True)),
                ('nombre_de_place', models.IntegerField(null=True)),
                ('type_de_voiture', models.CharField(choices=[('CITADINE', 'citadine'), ('CABRIOLET', 'cabriolet'), ('COUPÉ', 'coupé'), ('SUV', 'suv'), ('BERLINE', 'berline'), ('BREAK', 'break'), ('UTILITAIRE', 'utilitaire'), ('MONOSPACE', 'monospace'), ('AUTRES', 'autres')], max_length=20, null=True)),
                ('prix', models.FloatField(null=True)),
                ('reserver', models.BooleanField(default=False, null=True)),
                ('louer', models.BooleanField(default=False, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
